### ISSUE TITLE
eink: backlink document name whited out

### ISSUE THREAD

**Issue by derekvan** [kepano/obsidian-minimal#729]
### Is the bug present when using the default Obsidian theme?

Yes

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.6.3

### Describe the bug

Thanks for all these eink fixes! In the current version, the name of the document in the backlinks panel is whited out / invisible in the eink Theme.

![Screenshot 2024-05-14 at 3 21 38 PM](https://github.com/kepano/obsidian-minimal/assets/890341/0dc5a67b-4972-438c-b035-1f9e524de807)

### Debug info

SYSTEM INFO:
	Obsidian version: v1.6.0
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 23.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.6.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 26
		1: Dataview v0.5.64
		2: Extract PDF Annotations v1.0.4
		3: Kanban v1.5.3
		4: Obsidian better Internal Link Inserter v1.0.0
		5: Omnisearch v1.21.1
		6: Omnivore v1.9.4
		7: Zotero Integration v3.1.7
		8: Minimal Theme Settings v7.3.1
		9: Style Settings v1.0.8
		10: Pane Relief v0.5.3
		11: Copy Block Link v1.0.4
		12: Templater v2.2.3
		13: BRAT v0.8.4
		14: Outliner v4.8.0
		15: Zoom v1.1.2
		16: Commentator v0.1.4
		17: Chat View v1.6.0
		18: Strange New Worlds (SNW) v1.2.5
		19: Multiple Notes Outline v0.5.1
		20: PDF++ v0.37.15
		21: Hover Editor v0.11.17
		22: Breadcrumbs v4.0.86-beta
		23: Continuous Mode v1.1.0
		24: Grappling Hook v1.1.1
		25: Novel word count v3.9.0
		26: Link Nodes In Canvas v0.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
Go to Minimal Theme Settings and change the `Light mode background contrast` to `Default` or `Low contrast` mode rather than `All white` which is not supported in eink mode.

**Comment by kepano** [comment]
Fixed in 7.6.4

**Comment by derekvan** [comment]
I'm still getting this problem--and now additionally the file name on the selected tab is now whited out (after switching light mode to default and upgrading to 7.6.5)

SYSTEM INFO:
	Obsidian version: v1.6.0
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 23.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.6.5
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 26
		1: Dataview v0.5.64
		2: Extract PDF Annotations v1.0.4
		3: Kanban v1.5.3
		4: Obsidian better Internal Link Inserter v1.0.0
		5: Omnisearch v1.21.1
		6: Omnivore v1.9.4
		7: Zotero Integration v3.1.7
		8: Minimal Theme Settings v7.3.1
		9: Style Settings v1.0.8
		10: Pane Relief v0.5.3
		11: Copy Block Link v1.0.4
		12: Templater v2.2.3
		13: BRAT v0.8.4
		14: Outliner v4.8.0
		15: Zoom v1.1.2
		16: Commentator v0.1.4
		17: Chat View v1.6.0
		18: Strange New Worlds (SNW) v1.2.5
		19: Multiple Notes Outline v0.5.1
		20: PDF++ v0.37.15
		21: Hover Editor v0.11.17
		22: Breadcrumbs v4.0.86-beta
		23: Continuous Mode v1.1.0
		24: Grappling Hook v1.1.1
		25: Novel word count v3.9.0
		26: Link Nodes In Canvas v0.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
