### ISSUE TITLE
Exalidraw Bad buttons colors

### ISSUE THREAD

**Issue by dariuszkowalski-com** [kepano/obsidian-minimal#90]
**Describe the bug**
Bad colors of background element of Exalidraw interface when Theme of Exalidraw is not the same as theme of Obsidian.

problem is with:

```
body .excalidraw {
    --input-border-color: var(--background-modifier-border);
    --button-gray-1: var(--background-tertiary);
    --button-gray-2: var(--background-tertiary);
}
```

**To Reproduce**
I have got minimal theme installed, controlled by advanced apperance plugin

**Expected behavior**

Obsidian theme - Dark, Exalidraw "theme" - Light
![image](https://user-images.githubusercontent.com/37656900/147705913-9f2d06ad-bd2c-4bc0-a385-5e81c6ff51f2.png)

Obsidian theme - Light, Exalidraw "theme" - Dark
![image](https://user-images.githubusercontent.com/37656900/147705927-036df47b-dbb9-4205-90c9-86b5349ee8c4.png)

Screenshots

Obsidian theme - Dark, Exalidraw "theme" - Light
![image](https://user-images.githubusercontent.com/37656900/147705970-bd29fa4f-e203-4ff3-8f81-d7e7b80f2646.png)

Obsidian theme - Light, Exalidraw "theme" - Dark
![image](https://user-images.githubusercontent.com/37656900/147705944-8090d7cf-f650-4ef7-af68-db5f60c77f43.png)

**Desktop** :
OS: Windows 10
Browser: all
Version: Exalidraw: 1.5.7 , obsidian 0.13.16
Additional context
This problem start to appear when this options were added:

**Aditional**:
This problem start to appear when this options were added:
![image](https://user-images.githubusercontent.com/37656900/147706676-50d82f8f-26d9-4cac-a28e-1d7d24d40a70.png)

https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/326

**Comment by kepano** [comment]
This is fixed in Minimal 4.3

**Comment by dariuszkowalski-com** [comment]
There is the same issue with Obsidian Dark and Exalidraw Light:
![image](https://user-images.githubusercontent.com/37656900/147824836-f6f0af0d-b087-4311-aa54-d5bd6df1de1c.png)

Obsidian: 0.13.7 
Minimal-theme 4.3.1

**Comment by kepano** [comment]
This is now fixed in the latest commit, thanks!

**Comment by miluoshi** [comment]
I'm still encountering this issue. When themes match, colors are correct.

**Obsidian:** v0.13.23
**Minimal Theme Settings:** 5.0.4
**Minimal Theme:** 5.0.0
**Light mode color theme**: Nord; High contrast
**Dark mode color theme**: Things; Default

### Obsidian dark, Excalidraw light:
 
![image](https://user-images.githubusercontent.com/1130547/152657094-4cee4925-5b59-4683-a10f-d5fddb1965cf.png)

### Obsidian light, Excalidraw dark:
![image](https://user-images.githubusercontent.com/1130547/152657129-2ba9e14c-875c-4d7e-8d9f-44240cb88649.png)

### Both light
![image](https://user-images.githubusercontent.com/1130547/152657202-613102aa-26e3-40d4-b98a-dab070d612c0.png)

### Both dark
![image](https://user-images.githubusercontent.com/1130547/152657190-b9e51666-ee6d-4b05-aafe-9be195fbc62f.png)

**Comment by kepano** [comment]
This is fixed for now, but doesn't support the new Minimal color schemes.

A major part of the issue is that the Excalidraw plugin does not follow Obsidian's semantic variables. I think Excalidraw plugin should add theme compatibility by using Obsidian's CSS variables. This would improve things not just for Minimal but all other themes.

**Comment by miluoshi** [comment]
> This is fixed for now, but doesn't support the new Minimal color schemes.
> 
> A major part of the issue is that the Excalidraw plugin does not follow Obsidian's semantic variables. I think Excalidraw plugin should add theme compatibility by using Obsidian's CSS variables. This would improve things not just for Minimal but all other themes.

The plugin just embeds external application with its' own styles and I think there's no much control over styling of it.
But what I found is that Minimal theme actually already adds compatbility by reassigning Excalidraw's CSS variables to Obsidian ones [here](https://github.com/kepano/obsidian-minimal/blob/master/src/scss/plugins/excalidraw.scss#L3), but in incompatible way. 

Actually if I comment out this selector block, everything look alright. Is it really necessary for Minimal theme to override colors of css-variables of this plugin?
